# Generated by Django 4.1.5 on 2023-01-17 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
