# Generated by Django 4.1.6 on 2023-02-11 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("model", "0003_alter_employee_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="testing",
            field=models.CharField(default="testing", max_length=50),
        ),
    ]
