# Generated by Django 4.1.6 on 2023-02-13 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("model", "0004_employee_testing"),
    ]

    operations = [
        migrations.CreateModel(
            name="CardSets",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
            ],
        ),
    ]
