# Generated by Django 4.1.6 on 2023-02-13 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("model", "0005_cardsets"),
    ]

    operations = [
        migrations.AddField(
            model_name="cardsets",
            name="logo_image_url",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="cardsets",
            name="printed_total",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="cardsets",
            name="ptcgo_code",
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="cardsets",
            name="release_date",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="cardsets",
            name="series",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="cardsets",
            name="symbol_image_url",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="cardsets", name="total", field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="cardsets",
            name="unlimited_legality",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="cardsets",
            name="updated_at",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="cardsets",
            name="id",
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="cardsets",
            name="name",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
