# Generated by Django 4.1.7 on 2023-04-19 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0007_cart_customer_testtable_orders_orderdetails_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
